# Data Preparation Basis
## Tratando valores faltantes
Dados faltantes podem ser substituídos por:

- Média dos dados das linhas. Na maioria dos casos é melhor preencher os dados faltantes por dados aproximados do que deixá-los como 0.

In [ ]:
!pip install --upgrade pip
!pip install pandas

In [ ]:
# Importando as bibliotecas
import numpy as np
import pandas as pd
from pandas import DataFrame

## Preencher os dados faltantes usando fillna(), replace() e interpolate

In [ ]:
data = {'names':['steve','john','richard','sarah','randy','micheal','julie'],
        'age':[20,22,20,21,24,23,22],
        'gender':['Male','Male','Male','Female','Male','Male','Female'],
        'rank':[2,1,4,5,3,7,6]}
ranking_df = DataFrame(data)
ranking_df

     names  age  gender  rank
0    steve   20    Male     2
1     john   22    Male     1
2  richard   20    Male     4
3    sarah   21  Female     5
4    randy   24    Male     3
5  micheal   23    Male     7
6    julie   22  Female     6

In [ ]:
# Inserindo valores Nan
# Linhas 2:5 for (i=2;i<5;i++)
ranking_df.iloc[2:5,1] = np.nan
# Linhas 3:6 for (i=3;i<6;i++)
ranking_df.iloc[3:6,3] = np.nan
# ':' - Indica todas as colunas
ranking_df.iloc[3,:] = np.nan
ranking_df
ranking_df_original = ranking_df.copy()

## Descobrir o que está faltando (isnull() notnull())

In [ ]:
# Filtra dados faltantes
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [ ]:
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [ ]:
# Mostra dados faltantes em uma coluna específica.
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2  richard  NaN   Male   4.0
3      NaN  NaN    NaN   NaN
4    randy  NaN   Male   NaN

In [ ]:
# Preenche com zeros o que está com NaN
ranking_df.fillna(0)

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   0.0    Male   4.0
3        0   0.0       0   0.0
4    randy   0.0    Male   0.0
5  micheal  23.0    Male   0.0
6    julie  22.0  Female   6.0

In [ ]:
# Preenchendo os dados faltantes NaN com o último valor válido encontrado
# A linha 3 que estava toda NaN também será preenchida com o valor da linha anterior válida
# ranking_df.fillna(method='pad')
ranking_df.ffill()

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  22.0    Male   4.0
3  richard  22.0    Male   4.0
4    randy  22.0    Male   4.0
5  micheal  23.0    Male   4.0
6    julie  22.0  Female   6.0

In [ ]:
# Preencher Dados Faltantes com backfill (bfill) . Dó último valor válido para cima
# Agora a linha 3 foi preenchida com o valor da próxima linha válida
# ranking_df.fillna(method='bfill')
ranking_df.bfill()

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  23.0    Male   4.0
3    randy  23.0    Male   6.0
4    randy  23.0    Male   6.0
5  micheal  23.0    Male   6.0
6    julie  22.0  Female   6.0

In [ ]:
# Preenchendo com valores interpolados linearmente
# ranking_df.interpolate(method='linear')

# A linha acima gera erro pois tenta interpolar os textos.

# Interpola apenas as coluna numéricas
# ranking_df = ranking_df.copy()

numeric_cols = ranking_df.select_dtypes(include=['number']).columns
ranking_df[numeric_cols] = ranking_df[numeric_cols].interpolate(method='linear')
ranking_df

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
3      NaN  22.50     NaN   4.5
4    randy  22.75    Male   5.0
5  micheal  23.00    Male   5.5
6    julie  22.00  Female   6.0

In [ ]:
ranking_df_original

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [ ]:
# Apaga tudo que tem NaN 
ranking_df_original.dropna()

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0

In [ ]:
# Apaga apenas as colunas onde todos os valores são NaN
ranking_df_original.dropna(how='all')

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [ ]:
# Exclui todas as colunas que possuem pelo menos um valor NaN.
# ranking_df_original, possui a linha 3 com todos valores NaN
ranking_df_original.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [ ]:
ranking_df_original

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [ ]:
# Mostra somente as coluna que não tem valores faltantes
ranking_df_original.dropna(axis=0)

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0